// .res entries:
gfx/env/ntdm2_bk.tga
gfx/env/ntdm2_dn.tga
gfx/env/ntdm2_ft.tga
gfx/env/ntdm2_lf.tga
gfx/env/ntdm2_rt.tga
gfx/env/ntdm2_up.tga
models/ze_campescape_v1/antorcha_jairo.mdl
models/ze_campescape_v1/tren_mina.mdl
models/zombie_anthill/bush1.mdl
models/zombie_anthill/corpse1.mdl
models/zombie_anthill/corpse2.mdl
models/zombie_anthill/corpse4.mdl
models/zombie_anthill/forest1.mdl
sound/ambience/silo_wind_loop.wav
sound/ze_campescape_v1/campescape_jairo.wav
sound/ze_campescape_v1/flame.wav
sound/zombie_anthill/com_go_noiseup.wav
sound/zombie_anthill/fallback_noiseup.wav
sound/zombie_anthill/helicopter.wav
sound/zombie_anthill/resident_evil_main_theme.wav
sound/zombie_anthill/ze_ambiance1.wav
sprites/fire2_cz.spr
sprites/fire_cz.spr
sprites/flamefire.spr
gfx/detail/dt_conc.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_wood1.tga
maps/ze_campescape_b4_detail.txt